server:
  port: 0
spring:
  application:
    name: rest4
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        health-check-path: /isAlive
        health-check-interval: 2s
        instance-id: ${spring.application.name}:${random.value}







